version: "3"
services:
  discord-bot:
    restart: unless-stopped
    image: gdschongikoc/discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}
    volumes:
      - ${PWD}/serviceAccountKey.json:/app/lib/serviceAccountKey.json
