version: "3"
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - /redis_stack_data/:/data

  rating:
    depends_on:
      - redis
    restart: unless-stopped
    image: gdschongikoc/rating:latest
    ports:
      - 80:8000

  discord-bot:
    restart: unless-stopped
    image: gdschongikoc/discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}
