version: "3"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    expose:
      - 6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data

  rating:
    depends_on:
      - redis
    restart: unless-stopped
    image: gdschongikoc/rating:latest
    ports:
      - 80:8000

  discord-bot:
    restart: unless-stopped
    image: gdschongikoc/discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}
